apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss-digest
  labels:
    app: rss-digest
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - rss.germainleignel.com
      secretName: rss-digest-tls
  rules:
    - host: rss.germainleignel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rss-digest
                port:
                  number: 80
