apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-digest-data
  labels:
    app: rss-digest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
